Update QCPortal to have better CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,63 +1,90 @@
-language: python
+# After changing this file, check it on:
+#   http://lint.travis-ci.org/
+
 
 # Run jobs on container-based infrastructure, can be overridden per job
-dist: trusty
+sudo: false
+dist: xenial
+
+# Environment base builds
+language: generic
+os: linux
 
 matrix:
   include:
-    # Extra includes for OSX since python language is not available by default on OSX
-    - os: osx
-      language: generic
-      env: PYTHON_VER=3.5
-    - os: osx
-      language: generic
-      env: PYTHON_VER=3.6
-    - os: osx
-      language: generic
-      env: PYTHON_VER=3.7
 
-    - os: linux
-      python: 3.5
-      env: PYTHON_VER=3.5
-    - os: linux
-      python: 3.6
-      env: PYTHON_VER=3.6
-    - os: linux
-      python: 3.7
-      env: PYTHON_VER=3.7
+    - env:
+      - NAME="BASE 3.6"
+      - PYTHON_VER=3.6
+      - ENVIRON=BASE
+
+    - env:
+      - NAME="BASE 3.7"
+      - PYTHON_VER=3.7
+      - ENVIRON=BASE
+
+    - env:
+      - NAME="Adapters 3.6"
+      - PYTHON_VER=3.6
+      - ENVIRON=ADAPTERS
+
+    - env:
+      - NAME="OpenFF 3.6"
+      - PYTHON_VER=3.6
+      - ENVIRON=OPENFF
+
+    - env: &dev_head
+      - NAME="Development 3.7"
+      - PYTHON_VER=3.7
+      - ENVIRON=DEV_HEAD
+
   allow_failures:
-    - env: PYTHON_VER=3.7
-
+    - os: linux
+      env: *dev_head
 
 before_install:
-    # Additional info about the build
+  # Additional info about the build
   - uname -a
+  - free -m
   - df -h
   - ulimit -a
 
-    # Install the Python environment
+  # Setup python environment
   - source devtools/travis-ci/before_install.sh
   - python -V
 
 install:
-
     # Create test environment for package
-  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
-  - conda activate test
-
-    # Install pip only modules
-  - pip install codecov
+  - echo $ENVIRON
+  - |
+    if [ $ENVIRON == "ADAPTERS" ]; then
+      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/adapters.yaml
+    elif [ $ENVIRON == "OPENFF" ]; then
+      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/openff.yaml
+    elif [ $ENVIRON == "DEV_HEAD" ]; then
+      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/dev_head.yaml
+    elif [ $ENVIRON == "BASE" ]; then
+      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/base.yaml
+    else
+      echo "ERROR: No match for ENVIRON ($ENVIRON)."
+      exit 1
+    fi
+  - source activate test
 
     # Build and install package
-  - conda build --python=$PYTHON_VER devtools/conda-recipe
-  - conda install --use-local qcportal
+  - python setup.py develop --no-deps
 
+before_script:
+  - python -V
+  - conda list
 
 script:
   - pytest -v --cov=qcportal qcportal/tests/
+  - pytest -v --runexamples examples/
 
 notifications:
-    email: false
+  email: false
 
 after_success:
   - codecov
+
